### ISSUE TITLE
DFD Comments - Sept 20

### ISSUE THREAD

**Issue by germonprez** [Jrmelton/ISQA-3420#10]
Hi Jordan, 

A fairly simple comment: 

1) At the bottom of the DFD, Software Package and License Information --should be--> Software Package and License Information Request when going to the DB and --should be--> Software Package and License Information Response when coming back to the manager. 

2) Also you don't need the ERD.md. That file can be deleted. 

Matt

**Comment by Jrmelton** [comment]
Updating DFD with image
![dfdwithmanager](https://cloud.githubusercontent.com/assets/5325162/18723022/9f4ed87a-7ffc-11e6-9acd-71b796d3c733.png)

**Comment by germonprez** [comment]
Great!

**Comment by Jrmelton** [comment]
ERD.md file has also been deleted. Closing issue.
